# Specify the columns to check

features = ['year',
            'country',
            'biofuel_cons_change_pct',
                        'biofuel_cons_change_twh',
                        'biofuel_cons_per_capita',
                        'biofuel_consumption',
                        'biofuel_elec_per_capita',
                        'biofuel_electricity',
                        'biofuel_share_elec',
                        'biofuel_share_energy',
                        'hydro_cons_change_pct',
                        'hydro_cons_change_twh',
                        'hydro_consumption',
                        'hydro_elec_per_capita',
                        'hydro_electricity',
                        'hydro_energy_per_capita',
                        'hydro_share_elec',
                        'hydro_share_energy',
                        'other_renewable_consumption',
                        'other_renewable_electricity',
                        'other_renewable_exc_biofuel_electricity',
                        'other_renewables_cons_change_pct',
                        'other_renewables_cons_change_twh',
                        'other_renewables_elec_per_capita',
                        'other_renewables_elec_per_capita_exc_biofuel',
                        'other_renewables_energy_per_capita',
                        'other_renewables_share_elec',
                        'other_renewables_share_elec_exc_biofuel',
                        'other_renewables_share_energy',
                        'renewables_cons_change_pct',
                        'renewables_cons_change_twh',
                        'renewables_consumption',
                        'renewables_elec_per_capita',
                        'renewables_electricity',
                        'renewables_energy_per_capita',
                        'renewables_share_elec',
                        'renewables_share_energy',
                        'solar_cons_change_pct',
                        'solar_cons_change_twh',
                        'solar_consumption',
                        'solar_elec_per_capita',
                        'solar_electricity',
                        'solar_energy_per_capita',
                        'solar_share_elec',
                        'solar_share_energy',
                        'wind_cons_change_pct',
                        'wind_cons_change_twh',
                        'wind_consumption',
                        'wind_elec_per_capita',
                        'wind_electricity',
                        'wind_energy_per_capita',
                        'wind_share_elec',
                        'wind_share_energy',
                        'coal_cons_change_pct',
                        'coal_cons_change_twh',
                        'coal_cons_per_capita',
                        'coal_consumption',
                        'coal_elec_per_capita',
                        'coal_electricity',
                        'coal_prod_change_pct',
                        'coal_prod_change_twh',
                        'coal_prod_per_capita',
                        'coal_production',
                        'coal_share_elec',
                        'coal_share_energy',
                        'gas_cons_change_pct',
                        'gas_cons_change_twh',
                        'gas_consumption',
                        'gas_elec_per_capita',
                        'gas_electricity',
                        'gas_energy_per_capita',
                        'gas_prod_change_pct',
                        'gas_prod_change_twh',
                        'gas_prod_per_capita',
                        'gas_production',
                        'gas_share_elec',
                        'gas_share_energy',
                        'fossil_cons_change_pct',
                        'fossil_cons_change_twh',
                        'fossil_elec_per_capita',
                        'fossil_electricity',
                        'fossil_energy_per_capita',
                        'fossil_fuel_consumption',
                        'fossil_share_elec',
                        'fossil_share_energy',
]

additional_features = [
    'year',
    'country',
    ]






